# Generated by Django 4.0.2 on 2022-02-25 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cousename', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('mode', models.CharField(max_length=50)),
                ('institutename', models.CharField(max_length=100)),
                ('location', models.CharField(default='', max_length=100)),
                ('category', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=20)),
                ('details', models.CharField(max_length=999)),
                ('rooms', models.CharField(max_length=999)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
